server:
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres"
          host: "postgres-host"
          axiom_db: "postgres-db"
          port: 5432
          database: "temporal"
          user: "db-user"
          password: "db-password"
          existingSecret: ""
          sslMode: "postgres-ssl-mode"
          secretName: "db-secrets"
          configMapName: "database-connection"

      visibility:
        driver: "sql"
        sql:
          driver: "postgres"
          host: "postgres-host"
          axiom_db: "postgres-db"
          port: 5432
          database: "temporal_visibility"
          user: "db-user"
          password: "db-password"
          existingSecret: ""
          sslMode: "postgres-ssl-mode"
          secretName: "db-secrets"
          configMapName: "database-connection"

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: true

schema:
  setup:
    enabled: false
  update:
    enabled: false
